"""
Test data definitions: 25 candidates, 3 recruiters, 10 jobs
All passwords: Test@123
"""

PASSWORD = "Test@123"
BASE_URL = "http://localhost:8000"

RECRUITERS = [
    {"name": "Raj Kumar", "email": "recruiter1@test.com", "role": "RECRUITER", "company": "TCS", "password": PASSWORD},
    {"name": "Meera Joshi", "email": "recruiter2@test.com", "role": "RECRUITER", "company": "Infosys", "password": PASSWORD},
    {"name": "Amit Gupta", "email": "recruiter3@test.com", "role": "RECRUITER", "company": "Wipro", "password": PASSWORD},
]

# fmt: off
CANDIDATES = [
    # Frontend (5)
    {"name":"Ananya Sharma","email":"ananya.sharma@test.com","phone":"+91 9876543210","domain":"Frontend","skills":["React","JavaScript","HTML","CSS","TypeScript","Redux","Tailwind","Git"],"exp":[{"title":"Frontend Developer","company":"TechSoft Solutions","dates":"Jun 2022 - Present","bullets":["Built responsive React dashboards with Redux state management serving 50K+ users","Implemented TypeScript migration reducing runtime errors by 40%","Created reusable component library with 30+ components using Tailwind CSS","Collaborated with UX team to improve Core Web Vitals scores by 35%"]}],"edu":{"degree":"B.Tech in Computer Science","univ":"VIT University, Vellore","year":"2022","cgpa":"8.7"},"projects":[{"name":"E-Commerce Platform","desc":"Full-featured online store with React, Redux, and Stripe payment integration","tech":"React, Redux, Node.js, MongoDB, Stripe API"},{"name":"Weather Dashboard","desc":"Real-time weather tracking app with interactive maps and 5-day forecasts","tech":"React, OpenWeatherMap API, Chart.js, CSS Grid"}],"certs":["AWS Cloud Practitioner","Meta React Developer Certificate"],"summary":"Frontend developer with 2.5 years of experience building scalable React applications. Passionate about creating intuitive user interfaces with modern JavaScript frameworks.","format":"A"},
    {"name":"Ravi Teja","email":"ravi.teja@test.com","phone":"+91 9123456780","domain":"Frontend","skills":["Angular","TypeScript","SASS","Bootstrap","Node.js","REST API","Git","RxJS"],"exp":[{"title":"Senior UI Developer","company":"Wipro Technologies","dates":"Jan 2020 - Dec 2023","bullets":["Led Angular migration from AngularJS for enterprise banking application","Developed custom SASS design system adopted across 5 product teams","Integrated RESTful APIs with Angular services and RxJS observables","Mentored 3 junior developers on TypeScript best practices"]}],"edu":{"degree":"M.Tech in Information Technology","univ":"JNTU Hyderabad","year":"2019","cgpa":"8.9"},"projects":[{"name":"Banking Dashboard","desc":"Enterprise banking analytics dashboard with real-time data visualization","tech":"Angular, TypeScript, D3.js, SASS, REST APIs"}],"certs":["Google UX Design Certificate","Angular Advanced Certification"],"summary":"Experienced frontend developer with 4 years specializing in Angular and TypeScript. Strong background in enterprise application development and team mentoring.","format":"B"},
    {"name":"Divya Menon","email":"divya.menon@test.com","phone":"9988776655","domain":"Frontend","skills":["Vue","JavaScript","CSS","Webpack","Firebase","Jest","HTML","Vuex"],"exp":[{"title":"Junior Frontend Developer","company":"StartupHub Bangalore","dates":"Mar 2024 - Present","bullets":["Building Vue.js SPA for SaaS product with Vuex state management","Writing unit tests with Jest achieving 85% code coverage","Configured Webpack build pipeline reducing bundle size by 30%","Integrated Firebase authentication and real-time database"]}],"edu":{"degree":"BCA","univ":"Christ University, Bangalore","year":"2023","cgpa":"8.2"},"projects":[{"name":"Task Management App","desc":"Kanban-style task manager with drag-and-drop and real-time collaboration","tech":"Vue.js, Vuex, Firebase, CSS Animations"}],"certs":["freeCodeCamp JavaScript Certification"],"summary":"Creative frontend developer with 1 year experience in Vue.js ecosystem. Enthusiastic about building intuitive web applications with clean, tested code.","format":"C"},
    {"name":"Karthik Raj","email":"karthik.raj@test.com","phone":"+91-8765432109","domain":"Frontend","skills":["React","Next.js","JavaScript","Tailwind","GraphQL","Docker","AWS","Git","TypeScript"],"exp":[{"title":"React Developer","company":"Zoho Corporation","dates":"Aug 2021 - Present","bullets":["Developed Next.js SSR application improving SEO scores by 60%","Implemented GraphQL APIs with Apollo Client replacing REST endpoints","Deployed frontend applications on AWS using Docker containers","Built accessible UI components following WCAG 2.1 AA guidelines"]}],"edu":{"degree":"B.Tech in Electronics and Communication","univ":"Anna University, Chennai","year":"2021","cgpa":"8.4"},"projects":[{"name":"Portfolio Builder","desc":"Drag-and-drop portfolio website builder with Next.js and Tailwind","tech":"Next.js, React, Tailwind CSS, Vercel, PostgreSQL"}],"certs":["AWS Solutions Architect Associate","Udemy Next.js Complete Guide"],"summary":"Frontend developer with 3 years of experience in React and Next.js. Skilled in modern web technologies including GraphQL, Docker, and AWS deployment.","format":"A"},
    {"name":"Pooja Gupta","email":"pooja.gupta@test.com","phone":"7654321098","domain":"Frontend","skills":["React","HTML","CSS","jQuery","Bootstrap","JavaScript","Git"],"exp":[],"edu":{"degree":"B.Tech in Computer Science","univ":"BITS Pilani","year":"2024","cgpa":"7.8"},"projects":[{"name":"Student Portal","desc":"College student management system with attendance tracking and grade management","tech":"React, HTML, CSS, Bootstrap, Firebase"},{"name":"Recipe Finder","desc":"Recipe search app with filtering by ingredients, cuisine type, and dietary restrictions","tech":"React, Spoonacular API, CSS, Local Storage"},{"name":"Quiz Application","desc":"Interactive quiz platform with timer, score tracking, and leaderboard","tech":"React, JavaScript, CSS Animations, JSON"}],"certs":["Coursera React Basics","HackerRank JavaScript Gold Badge","Udemy Web Development Bootcamp"],"summary":"Enthusiastic B.Tech fresher with strong foundation in React and web development. Built multiple full-stack projects during academics. Eager to contribute to innovative frontend teams.","format":"E"},
    # Backend (5)
    {"name":"Arun Kumar","email":"arun.kumar@test.com","phone":"+91 8899776655","domain":"Backend","skills":["Python","Django","PostgreSQL","REST API","Docker","Redis","Linux","Git","Celery","Nginx"],"exp":[{"title":"Senior Python Developer","company":"Infosys Limited","dates":"Jan 2019 - Present","bullets":["Architected Django REST APIs serving 100K+ daily requests with sub-200ms response time","Implemented Redis caching layer reducing database load by 60%","Set up Docker containerized deployment with Nginx reverse proxy","Designed PostgreSQL schemas for multi-tenant SaaS application","Led team of 4 developers for microservices migration project"]},{"title":"Python Developer","company":"Cognizant","dates":"Jul 2017 - Dec 2018","bullets":["Built RESTful APIs using Django REST Framework for e-commerce platform","Wrote automated tests with pytest achieving 90% code coverage","Implemented Celery task queues for async email and report generation"]}],"edu":{"degree":"M.Tech in Computer Science","univ":"IIT Madras","year":"2017","cgpa":"9.1"},"projects":[],"certs":["AWS Developer Associate","Docker Certified Associate"],"summary":"Senior Python developer with 5+ years building scalable backend systems. Expert in Django, PostgreSQL, and containerized deployments. Strong focus on API performance and code quality.","format":"B"},
    {"name":"Meghana Rao","email":"meghana.rao@test.com","phone":"+91-7788996655","domain":"Backend","skills":["Java","Spring Boot","MySQL","Microservices","AWS","Jenkins","Git","JUnit","Kafka","Docker"],"exp":[{"title":"Lead Java Developer","company":"TCS Digital","dates":"Mar 2018 - Present","bullets":["Designed microservices architecture handling 500K transactions per day","Built Spring Boot REST APIs with OAuth2 security and rate limiting","Implemented CI/CD pipelines with Jenkins reducing deployment time by 70%","Managed AWS infrastructure including EC2, RDS, and S3","Set up Kafka event streaming for real-time order processing","Conducted code reviews and established coding standards for 8-member team"]}],"edu":{"degree":"B.Tech in Information Technology","univ":"NIT Warangal","year":"2017","cgpa":"8.6"},"projects":[],"certs":["Oracle Certified Java Professional","AWS Solutions Architect"],"summary":"Lead Java developer with 6 years of experience in enterprise microservices. Expertise in Spring Boot, AWS, and high-throughput distributed systems.","format":"A"},
    {"name":"Farhan Ahmed","email":"farhan.ahmed@test.com","phone":"9977886655","domain":"Backend","skills":["Node.js","Express","MongoDB","REST API","JWT","Redis","JavaScript","Git"],"exp":[{"title":"Backend Developer","company":"Freshworks","dates":"Jan 2022 - Dec 2023","bullets":["Built Express.js REST APIs for customer support ticketing system","Implemented JWT authentication with refresh token rotation","Designed MongoDB schemas with aggregation pipelines for analytics"]},{"title":"Junior Developer","company":"Startup XYZ","dates":"Aug 2023 - May 2024","bullets":["Developed real-time chat API using WebSockets and Redis pub/sub","Created automated API documentation with Swagger/OpenAPI","Optimized MongoDB queries reducing response times by 45%"]}],"edu":{"degree":"B.Tech in Computer Science","univ":"Osmania University, Hyderabad","year":"2021","cgpa":"7.9"},"projects":[{"name":"Chat Application","desc":"Real-time messaging platform with group chats, file sharing, and read receipts","tech":"Node.js, Socket.io, MongoDB, Redis"}],"certs":["MongoDB Developer Certification"],"summary":"Backend developer with 2 years of experience in Node.js and MongoDB. Skilled in building real-time applications and RESTful APIs with strong security practices.","format":"C"},
    {"name":"Sneha Iyer","email":"sneha.iyer@test.com","phone":"+91 8866554433","domain":"Backend","skills":["Python","FastAPI","PostgreSQL","Docker","Kubernetes","CI/CD","Git","Redis","Linux","Pytest"],"exp":[{"title":"Python Backend Engineer","company":"Razorpay","dates":"Jul 2021 - Present","bullets":["Developed FastAPI microservices for payment processing handling 10K TPS","Deployed services on Kubernetes clusters with auto-scaling policies","Built CI/CD pipelines with GitHub Actions for automated testing and deployment","Implemented connection pooling and Redis caching for database optimization","Wrote comprehensive pytest suites with 95% coverage for critical payment flows"]}],"edu":{"degree":"M.Tech in Computer Science","univ":"IIIT Hyderabad","year":"2021","cgpa":"9.0"},"projects":[],"certs":["Certified Kubernetes Administrator","Python Professional Certificate"],"summary":"Backend engineer with 3.5 years specializing in Python FastAPI and cloud-native development. Experience with high-throughput payment systems and Kubernetes orchestration.","format":"B"},
    {"name":"Vikram Desai","email":"vikram.desai@test.com","phone":"+91-9955443322","domain":"Backend","skills":["Go","gRPC","PostgreSQL","Kafka","Docker","Kubernetes","AWS","Terraform","Linux","Git","Prometheus"],"exp":[{"title":"Staff Engineer","company":"Flipkart","dates":"Feb 2017 - Present","bullets":["Architected Go microservices handling 1M+ RPM for product catalog","Designed gRPC service mesh with circuit breakers and load balancing","Built real-time event streaming pipelines with Kafka processing 5TB daily","Managed Kubernetes clusters across 3 AWS regions with Terraform IaC","Implemented observability stack with Prometheus, Grafana, and distributed tracing","Led architecture review board and mentored 10+ engineers"]}],"edu":{"degree":"B.Tech in Computer Science","univ":"IIT Bombay","year":"2016","cgpa":"9.3"},"projects":[],"certs":["AWS Solutions Architect Professional","HashiCorp Terraform Associate"],"summary":"Staff engineer with 7+ years building large-scale distributed systems in Go. Expert in microservices, event streaming, and cloud infrastructure at scale.","format":"A"},
]
# fmt: on

# Part 2 will be in seed_data2.py
