"""
Remaining 15 candidates (Data Science, DevOps, Full Stack, Freshers) + Jobs + Application mapping
"""
from seed_data import PASSWORD

# fmt: off
CANDIDATES_PART2 = [
    # Data Science / ML (5)
    {"name":"Priya Patel","email":"priya.patel@test.com","phone":"+91 7766554433","domain":"DataScience","skills":["Python","Pandas","NumPy","Scikit-learn","SQL","Tableau","Excel","Statistics","Matplotlib","Data Analysis"],"exp":[{"title":"Data Analyst","company":"Accenture","dates":"Jan 2023 - Present","bullets":["Analyzed customer behavior datasets of 2M+ records using Pandas and SQL","Built interactive Tableau dashboards for C-suite executives tracking KPIs","Applied statistical hypothesis testing for A/B experiments improving conversion by 12%","Automated Excel reporting pipelines with Python saving 15 hours weekly","Created data quality monitoring scripts catching anomalies in real-time"]}],"edu":{"degree":"M.Sc in Statistics","univ":"Indian Statistical Institute, Kolkata","year":"2022","cgpa":"9.2"},"projects":[{"name":"Sales Forecasting Model","desc":"Time-series forecasting model for retail sales using ARIMA and Prophet","tech":"Python, Pandas, Statsmodels, Prophet, Matplotlib"}],"certs":["Google Data Analytics Certificate","Tableau Desktop Specialist"],"summary":"Data analyst with 2 years of experience in Python and statistical analysis. Strong background in data visualization, business intelligence, and deriving actionable insights from complex datasets.","format":"C"},
    {"name":"Rohit Saxena","email":"rohit.saxena@test.com","phone":"8855443322","domain":"ML","skills":["Python","TensorFlow","PyTorch","Deep Learning","NLP","OpenCV","AWS","Keras","NumPy","Pandas","Docker","Scikit-learn"],"exp":[{"title":"ML Engineer","company":"Samsung R&D","dates":"Jun 2020 - Present","bullets":["Developed NLP models for sentiment analysis achieving 94% accuracy on product reviews","Built computer vision pipeline with OpenCV and TensorFlow for defect detection","Deployed ML models on AWS SageMaker with auto-scaling inference endpoints","Implemented transfer learning using pre-trained BERT models for text classification","Designed data augmentation strategies improving model accuracy by 8%","Published 2 internal research papers on deep learning optimization techniques"]}],"edu":{"degree":"M.Tech in Artificial Intelligence","univ":"IISc Bangalore","year":"2020","cgpa":"9.4"},"projects":[],"certs":["TensorFlow Developer Certificate","AWS Machine Learning Specialty"],"summary":"ML engineer with 4 years of experience in deep learning, NLP, and computer vision. Published researcher with expertise in TensorFlow, PyTorch, and production ML systems.","format":"B"},
    {"name":"Lakshmi Nair","email":"lakshmi.nair@test.com","phone":"+91-7744332211","domain":"DataAnalysis","skills":["Python","Pandas","Power BI","SQL","Data Analysis","Excel","Statistics","Matplotlib","Seaborn"],"exp":[{"title":"Business Analyst","company":"Deloitte India","dates":"Jul 2023 - Present","bullets":["Created Power BI dashboards tracking revenue metrics across 12 business units","Wrote complex SQL queries for data extraction from Oracle data warehouse","Performed exploratory data analysis on customer churn reducing attrition by 8%","Automated monthly reporting with Python scripts replacing manual Excel processes","Presented analytical findings to stakeholders driving strategic business decisions"]}],"edu":{"degree":"MBA in Business Analytics","univ":"Symbiosis International University, Pune","year":"2023","cgpa":"8.5"},"projects":[{"name":"Customer Segmentation","desc":"RFM analysis and K-Means clustering for targeted marketing campaigns","tech":"Python, Pandas, Scikit-learn, Power BI"}],"certs":["Microsoft Power BI Data Analyst","SQL Advanced HackerRank"],"summary":"Business analyst with 1.5 years of experience in data analytics and Power BI visualization. MBA graduate combining business acumen with technical data analysis skills.","format":"D"},
    {"name":"Siddharth Jain","email":"siddharth.jain@test.com","phone":"9933221100","domain":"ML","skills":["Python","Machine Learning","Scikit-learn","Pandas","NumPy","Flask","SQL","TensorFlow","Git","Linux"],"exp":[{"title":"Data Scientist","company":"Mu Sigma","dates":"Apr 2021 - Present","bullets":["Built recommendation engine using collaborative filtering serving 500K users","Developed churn prediction models with XGBoost achieving 89% AUC-ROC","Created Flask APIs for real-time ML model inference with sub-100ms latency","Designed feature engineering pipelines processing 10GB+ datasets daily","Conducted A/B tests for model performance validation in production"]}],"edu":{"degree":"M.Tech in Computer Science","univ":"BITS Pilani","year":"2021","cgpa":"8.8"},"projects":[],"certs":["Coursera Machine Learning Specialization","Google Cloud ML Engineer"],"summary":"Data scientist with 3 years building production ML systems. Expert in predictive modeling, feature engineering, and deploying ML models as scalable APIs.","format":"A"},
    {"name":"Tanvi Deshmukh","email":"tanvi.deshmukh@test.com","phone":"+91 6655443322","domain":"Data","skills":["R","Python","Statistics","Data Analysis","Excel","Tableau","SQL"],"exp":[],"edu":{"degree":"B.Sc in Statistics","univ":"Fergusson College, Pune","year":"2024","cgpa":"8.0"},"projects":[{"name":"COVID-19 Data Dashboard","desc":"Interactive dashboard tracking pandemic trends with statistical analysis and predictions","tech":"R, Shiny, ggplot2, dplyr, COVID-19 API"},{"name":"Sentiment Analysis Tool","desc":"Twitter sentiment analyzer using NLP techniques for brand monitoring","tech":"Python, NLTK, TextBlob, Pandas, Matplotlib"},{"name":"Survey Data Analysis","desc":"Statistical analysis of educational survey data with hypothesis testing","tech":"R, Excel, SPSS, ggplot2"}],"certs":["Coursera Statistics with R","DataCamp Data Analyst Track","Google Sheets Advanced"],"summary":"Statistics graduate with strong analytical skills and passion for data-driven insights. Experienced in R, Python, and statistical modeling through academic projects and coursework.","format":"E"},
    # DevOps (4)
    {"name":"Ajay Mishra","email":"ajay.mishra@test.com","phone":"+91 5544332211","domain":"DevOps","skills":["AWS","Docker","Kubernetes","Terraform","Jenkins","Linux","Bash","Python","CI/CD","Ansible","Prometheus","Grafana"],"exp":[{"title":"Senior DevOps Engineer","company":"Amazon India","dates":"Jan 2019 - Present","bullets":["Managed 50+ microservices deployment on EKS clusters across 3 regions","Built Terraform IaC modules for complete AWS infrastructure provisioning","Designed Jenkins CI/CD pipelines reducing release cycles from weekly to daily","Implemented Prometheus and Grafana monitoring stack with 200+ alerts","Automated server provisioning with Ansible reducing setup time by 80%","Achieved 99.99% uptime SLA for production services"]}],"edu":{"degree":"B.Tech in Computer Science","univ":"NIT Trichy","year":"2018","cgpa":"8.5"},"projects":[],"certs":["AWS DevOps Professional","Certified Kubernetes Administrator","HashiCorp Terraform Associate"],"summary":"Senior DevOps engineer with 5+ years managing large-scale cloud infrastructure. Expert in AWS, Kubernetes, and infrastructure automation with strong focus on reliability.","format":"A"},
    {"name":"Neha Kapoor","email":"neha.kapoor@test.com","phone":"8833221100","domain":"DevOps","skills":["Azure","Docker","Ansible","Jenkins","Git","Python","Linux","Kubernetes","CI/CD","Terraform"],"exp":[{"title":"DevOps Engineer","company":"HCL Technologies","dates":"Feb 2021 - Present","bullets":["Managed Azure DevOps pipelines for 20+ .NET and Java applications","Containerized legacy applications using Docker reducing resource usage by 40%","Implemented Ansible playbooks for configuration management across 100+ servers","Built Kubernetes deployment manifests with Helm charts for microservices","Set up centralized logging with ELK stack for production troubleshooting"]}],"edu":{"degree":"M.Tech in Information Technology","univ":"Delhi Technological University","year":"2020","cgpa":"8.7"},"projects":[{"name":"Infrastructure Dashboard","desc":"Real-time infrastructure health monitoring dashboard with alerting","tech":"Python, Flask, Azure Monitor, Grafana"}],"certs":["Azure DevOps Engineer Expert","Docker Certified Associate"],"summary":"DevOps engineer with 3 years specializing in Azure cloud and container orchestration. Strong background in CI/CD automation and infrastructure management.","format":"C"},
    {"name":"Srinivas Rao","email":"srinivas.rao@test.com","phone":"+91-7722110099","domain":"Cloud","skills":["AWS","EC2","S3","Lambda","CloudFormation","Docker","Linux","Python","Bash","IAM"],"exp":[{"title":"Cloud Engineer","company":"Wipro","dates":"Aug 2022 - Present","bullets":["Provisioned and managed 30+ EC2 instances with auto-scaling groups","Built serverless applications using AWS Lambda and API Gateway","Created CloudFormation templates for repeatable infrastructure deployment","Configured IAM policies and security groups following least privilege principle","Managed S3 lifecycle policies optimizing storage costs by 25%"]}],"edu":{"degree":"B.Tech in Electronics and Communication","univ":"SRM University, Chennai","year":"2022","cgpa":"7.6"},"projects":[{"name":"Serverless API","desc":"REST API built entirely on AWS serverless stack with DynamoDB backend","tech":"AWS Lambda, API Gateway, DynamoDB, CloudFormation"}],"certs":["AWS Cloud Practitioner","AWS Solutions Architect Associate"],"summary":"Cloud engineer with 2 years of hands-on experience in AWS. Skilled in serverless architecture, infrastructure as code, and cloud security best practices.","format":"D"},
    {"name":"Deepak Thakur","email":"deepak.thakur@test.com","phone":"6611009988","domain":"DevOps","skills":["GCP","Docker","Kubernetes","Terraform","GitHub Actions","Python","Bash","Linux","Helm","Istio"],"exp":[{"title":"Platform Engineer","company":"Google India","dates":"Jun 2020 - Present","bullets":["Built GKE-based platform serving 200+ internal microservices","Designed Terraform modules for GCP infrastructure with Terragrunt","Implemented GitHub Actions CI/CD reducing build times by 50%","Deployed Istio service mesh for traffic management and security","Automated cluster upgrades and node pool management with Python scripts","Maintained Helm chart repository for standardized application deployment"]}],"edu":{"degree":"B.Tech in Computer Science","univ":"IIIT Delhi","year":"2020","cgpa":"8.3"},"projects":[],"certs":["Google Cloud Professional DevOps Engineer","CKA Certified"],"summary":"Platform engineer with 4 years building cloud-native platforms on GCP. Expert in Kubernetes, Terraform, and modern CI/CD practices for developer productivity.","format":"B"},
    # Full Stack (3) - #22 has Java+JavaScript edge case
    {"name":"Amit Patil","email":"amit.patil@test.com","phone":"+91 5500998877","domain":"FullStack","skills":["React","Node.js","MongoDB","Express","JavaScript","HTML","CSS","AWS","Docker","Git","REST API","TypeScript"],"exp":[{"title":"Full Stack Developer","company":"Mindtree","dates":"Mar 2020 - Present","bullets":["Built end-to-end MERN stack applications for fintech clients","Developed React frontend with Redux and Node.js REST API backend","Deployed applications on AWS EC2 with Docker containerization","Implemented real-time features using Socket.io for collaboration tools","Designed MongoDB schemas with indexing strategies for optimal query performance","Led code reviews and established Git branching strategy for 6-member team"]}],"edu":{"degree":"B.Tech in Information Technology","univ":"Pune University","year":"2019","cgpa":"8.1"},"projects":[],"certs":["MongoDB Developer Certification","AWS Cloud Practitioner"],"summary":"Full stack developer with 4 years of MERN stack expertise. Experienced in building scalable web applications with modern JavaScript technologies and cloud deployment.","format":"A"},
    {"name":"Swati Kulkarni","email":"swati.kulkarni@test.com","phone":"9900887766","domain":"FullStack","skills":["Angular","Python","Django","PostgreSQL","HTML","CSS","REST API","Docker","Git","TypeScript","Redis"],"exp":[{"title":"Full Stack Engineer","company":"ThoughtWorks","dates":"Jun 2022 - Present","bullets":["Developed Angular frontend with Django REST backend for healthcare platform","Designed PostgreSQL database schemas with complex relationships and views","Implemented Redis caching for frequently accessed patient records","Built Docker development environments for consistent team onboarding","Created comprehensive API documentation with DRF Spectacular"]}],"edu":{"degree":"M.Tech in Computer Science","univ":"IIT Kanpur","year":"2022","cgpa":"9.0"},"projects":[{"name":"Healthcare Portal","desc":"Patient management system with appointment scheduling and medical records","tech":"Angular, Django, PostgreSQL, Docker, Redis"}],"certs":["Django Developer Certificate","Angular Advanced Training"],"summary":"Full stack engineer with 2.5 years combining Angular frontend with Python Django backend. Strong focus on clean architecture and test-driven development.","format":"C"},
    {"name":"Manish Pandey","email":"manish.pandey@test.com","phone":"+91-8899001122","domain":"FullStack","skills":["Vue","FastAPI","MongoDB","JavaScript","Python","Docker","Redis","JWT","Java","HTML","CSS","Git"],"exp":[{"title":"Software Developer","company":"Capgemini","dates":"Jul 2023 - Present","bullets":["Building Vue.js SPA with FastAPI backend for inventory management system","Implemented JWT authentication with role-based access control","Developed Java microservices for legacy system integration","Designed MongoDB collections with aggregation pipelines for reporting","Configured Docker Compose for multi-service local development"]}],"edu":{"degree":"B.Tech in Computer Science","univ":"LNMIIT Jaipur","year":"2023","cgpa":"7.7"},"projects":[{"name":"Inventory Manager","desc":"Real-time inventory tracking system with barcode scanning and alerts","tech":"Vue.js, FastAPI, MongoDB, Docker, WebSockets"}],"certs":["Oracle Certified Java Foundations","Python PCEP Certification"],"summary":"Software developer with 1.5 years working across Vue.js, FastAPI, and Java. Versatile full stack developer comfortable with both JavaScript and Python ecosystems.","format":"D"},
    # Freshers (3)
    {"name":"Sakshi Joshi","email":"sakshi.joshi@test.com","phone":"7700889966","domain":"Fresher","skills":["Python","HTML","CSS","SQL","Git","Flask","JavaScript"],"exp":[],"edu":{"degree":"B.Tech in Computer Science","univ":"Amity University, Noida","year":"2024","cgpa":"8.3"},"projects":[{"name":"Library Management System","desc":"Complete library system with book tracking, member management, and fine calculation","tech":"Python, Flask, SQLite, HTML, CSS, Bootstrap"},{"name":"Personal Blog","desc":"Dynamic blog platform with markdown support, comments, and admin panel","tech":"Python, Flask, PostgreSQL, HTML, CSS, JavaScript"},{"name":"Expense Tracker","desc":"Monthly expense tracking application with charts and category-wise breakdown","tech":"Python, Flask, SQLite, Chart.js, Bootstrap"}],"certs":["Python for Everybody (Coursera)","SQL Basics (HackerRank Gold)","Web Development Fundamentals (Udemy)","Git and GitHub Masterclass"],"summary":"B.Tech Computer Science graduate with strong Python fundamentals. Built multiple web applications using Flask during academics. Quick learner eager to start career in software development.","format":"E"},
    {"name":"Nikhil Sharma","email":"nikhil.sharma@test.com","phone":"+91 6600778855","domain":"Fresher","skills":["Java","Python","MySQL","HTML","CSS","Git","Spring Boot"],"exp":[],"edu":{"degree":"B.Tech in Information Technology","univ":"Chandigarh University","year":"2024","cgpa":"7.5"},"projects":[{"name":"Online Exam Portal","desc":"Web-based examination system with auto-grading, timer, and result analytics","tech":"Java, Spring Boot, MySQL, Thymeleaf, Bootstrap"},{"name":"Student Attendance System","desc":"QR-code based attendance tracking with admin dashboard and reports","tech":"Java, Spring Boot, MySQL, HTML, JavaScript"},{"name":"Chat Bot","desc":"Rule-based customer support chatbot with FAQ matching and ticket creation","tech":"Python, NLTK, Flask, HTML, CSS"}],"certs":["Java Programming (Coursera)","MySQL for Data Analytics","Spring Boot Essentials (Udemy)","Python Basics (Kaggle)"],"summary":"B.Tech IT graduate with strong foundation in Java and Python. Developed multiple academic projects using Spring Boot and Flask. Passionate about backend development and eager to learn.","format":"E"},
    {"name":"Ishita Agarwal","email":"ishita.agarwal@test.com","phone":"5500667744","domain":"Fresher","skills":["JavaScript","React","HTML","CSS","MongoDB","Node.js","Git"],"exp":[],"edu":{"degree":"BCA","univ":"Symbiosis Institute, Pune","year":"2024","cgpa":"8.1"},"projects":[{"name":"Social Media Dashboard","desc":"Social media analytics dashboard with post scheduling and engagement tracking","tech":"React, Node.js, MongoDB, Express, Chart.js"},{"name":"Food Delivery Clone","desc":"Swiggy-inspired food ordering app with cart, payment mock, and order tracking","tech":"React, Node.js, MongoDB, Express, CSS"},{"name":"Portfolio Website","desc":"Personal portfolio with project showcase, contact form, and blog section","tech":"React, CSS Animations, EmailJS, Netlify"}],"certs":["Meta Frontend Developer Certificate","freeCodeCamp Full Stack","JavaScript Algorithms (HackerRank Gold)","React Complete Guide (Udemy)"],"summary":"BCA graduate with passion for full-stack web development. Built multiple MERN stack projects including a social media dashboard and food delivery clone. Ready to contribute to dynamic development teams.","format":"E"},
]
# fmt: on

JOBS = [
    {"title":"React Frontend Developer","company":"TCS","recruiter_email":"recruiter1@test.com","location":"Mumbai, India","jobType":"Full-time","workplaceType":"On-site","numberOfOpenings":3,"requiredSkills":["React","JavaScript","HTML","CSS","Git"],"preferredSkills":["TypeScript","Redux","Tailwind"],"minExperience":2,"maxExperience":5,"educationLevel":"Bachelor's Degree","salaryMin":600000,"salaryMax":1200000,"description":"We are looking for a skilled React Frontend Developer to join our team at TCS Mumbai. The ideal candidate will have strong experience with React.js and modern JavaScript development.\n\nResponsibilities:\n- Develop and maintain React-based web applications\n- Write clean, maintainable code following best practices\n- Collaborate with backend teams on REST API integration\n- Implement responsive designs and cross-browser compatibility\n- Participate in code reviews and technical discussions\n\nRequired Skills:\n- React.js with 2+ years of hands-on experience\n- Strong JavaScript and ES6+ fundamentals\n- HTML5 and CSS3 proficiency\n- Version control with Git\n- Understanding of RESTful APIs\n\nPreferred Skills:\n- TypeScript experience\n- State management with Redux\n- Tailwind CSS or similar utility frameworks\n\nEducation: Bachelor's degree in Computer Science or related field\nExperience: Minimum 2 years of frontend development experience"},
    {"title":"Senior Python Backend Engineer","company":"Infosys","recruiter_email":"recruiter1@test.com","location":"Bangalore, India","jobType":"Full-time","workplaceType":"Hybrid","numberOfOpenings":2,"requiredSkills":["Python","Django","PostgreSQL","REST API","Docker"],"preferredSkills":["Redis","Kubernetes","CI/CD"],"minExperience":4,"maxExperience":8,"educationLevel":"Bachelor's Degree","salaryMin":1200000,"salaryMax":2000000,"description":"Infosys is hiring a Senior Python Backend Engineer for our Bangalore office. You will architect and build scalable backend systems powering enterprise applications.\n\nResponsibilities:\n- Design and implement Python-based backend services\n- Build RESTful APIs using Django REST Framework\n- Manage PostgreSQL databases with performance optimization\n- Containerize applications using Docker\n- Lead technical design discussions and mentor junior developers\n\nRequired Skills:\n- Python with 4+ years of backend development\n- Django or Django REST Framework expertise\n- PostgreSQL database design and optimization\n- REST API development best practices\n- Docker containerization\n\nPreferred Skills:\n- Redis caching experience\n- Kubernetes orchestration\n- CI/CD pipeline setup\n\nEducation: Bachelor's degree in Computer Science or equivalent\nExperience: Minimum 4 years of Python backend development"},
    {"title":"Data Analyst","company":"Wipro","recruiter_email":"recruiter2@test.com","location":"Hyderabad, India","jobType":"Full-time","workplaceType":"On-site","numberOfOpenings":4,"requiredSkills":["Python","SQL","Excel","Data Analysis","Statistics"],"preferredSkills":["Tableau","Power BI","Pandas"],"minExperience":1,"maxExperience":4,"educationLevel":"Any Degree","salaryMin":400000,"salaryMax":800000,"description":"Wipro is seeking a Data Analyst to join our analytics team in Hyderabad. You will transform raw data into meaningful business insights.\n\nResponsibilities:\n- Analyze large datasets using Python and SQL\n- Create reports and dashboards for business stakeholders\n- Perform statistical analysis and hypothesis testing\n- Maintain data quality and documentation\n- Collaborate with business teams to understand requirements\n\nRequired Skills:\n- Python for data manipulation and analysis\n- SQL for database querying and data extraction\n- Advanced Excel including pivot tables and VLOOKUP\n- Strong data analysis and problem-solving skills\n- Statistical knowledge including hypothesis testing\n\nPreferred Skills:\n- Tableau or Power BI visualization\n- Pandas library proficiency\n- Experience with data warehousing concepts\n\nEducation: Any degree with analytical background\nExperience: Minimum 1 year of data analysis experience"},
    {"title":"ML Engineer","company":"Google India","recruiter_email":"recruiter2@test.com","location":"Bangalore, India","jobType":"Full-time","workplaceType":"Hybrid","numberOfOpenings":2,"requiredSkills":["Python","TensorFlow","Machine Learning","Deep Learning"],"preferredSkills":["PyTorch","NLP","AWS"],"minExperience":3,"maxExperience":7,"educationLevel":"Master's Degree","salaryMin":2000000,"salaryMax":4000000,"description":"Google India is looking for an ML Engineer to build next-generation machine learning systems. Join our team to work on cutting-edge AI problems at scale.\n\nResponsibilities:\n- Design and train machine learning models for production use\n- Implement deep learning architectures for NLP and computer vision\n- Deploy models with scalable inference pipelines\n- Collaborate with research teams on novel ML approaches\n- Monitor model performance and implement retraining strategies\n\nRequired Skills:\n- Python with strong ML/DL expertise\n- TensorFlow framework proficiency\n- Machine learning algorithms and theory\n- Deep learning architectures (CNN, RNN, Transformers)\n\nPreferred Skills:\n- PyTorch experience\n- Natural Language Processing\n- AWS/GCP ML services\n\nEducation: Master's degree in CS, AI, or related field\nExperience: Minimum 3 years of ML engineering experience"},
    {"title":"DevOps Engineer","company":"Amazon India","recruiter_email":"recruiter3@test.com","location":"Hyderabad, India","jobType":"Full-time","workplaceType":"On-site","numberOfOpenings":3,"requiredSkills":["AWS","Docker","Kubernetes","Linux","CI/CD"],"preferredSkills":["Terraform","Jenkins","Ansible"],"minExperience":3,"maxExperience":7,"educationLevel":"Bachelor's Degree","salaryMin":1500000,"salaryMax":2500000,"description":"Amazon India is hiring a DevOps Engineer for our Hyderabad development center. You will manage cloud infrastructure and build automation pipelines for our services.\n\nResponsibilities:\n- Manage AWS cloud infrastructure for production workloads\n- Build and maintain Docker containers and Kubernetes clusters\n- Design CI/CD pipelines for automated testing and deployment\n- Ensure high availability and disaster recovery\n- Implement monitoring and alerting systems\n\nRequired Skills:\n- AWS services (EC2, S3, EKS, IAM)\n- Docker containerization\n- Kubernetes orchestration\n- Linux system administration\n- CI/CD pipeline development\n\nPreferred Skills:\n- Terraform infrastructure as code\n- Jenkins pipeline scripting\n- Ansible configuration management\n\nEducation: Bachelor's degree in Computer Science or related field\nExperience: Minimum 3 years of DevOps experience"},
    {"title":"Full Stack Developer","company":"Microsoft","recruiter_email":"recruiter3@test.com","location":"Noida, India","jobType":"Full-time","workplaceType":"Hybrid","numberOfOpenings":3,"requiredSkills":["React","Node.js","MongoDB","JavaScript","REST API"],"preferredSkills":["Docker","AWS","TypeScript"],"minExperience":2,"maxExperience":5,"educationLevel":"Bachelor's Degree","salaryMin":1000000,"salaryMax":1800000,"description":"Microsoft India is looking for a Full Stack Developer to build web applications using modern JavaScript technologies. Join our Noida office to work on impactful products.\n\nResponsibilities:\n- Develop full-stack applications using React and Node.js\n- Design and implement MongoDB database schemas\n- Build RESTful APIs with Express.js\n- Write unit and integration tests\n- Collaborate in agile development sprints\n\nRequired Skills:\n- React.js frontend development\n- Node.js backend development\n- MongoDB database management\n- JavaScript ES6+ proficiency\n- REST API design and implementation\n\nPreferred Skills:\n- Docker containerization\n- AWS cloud services\n- TypeScript experience\n\nEducation: Bachelor's degree in Computer Science or related field\nExperience: Minimum 2 years of full-stack development"},
    {"title":"Junior Frontend Developer","company":"Zoho","recruiter_email":"recruiter1@test.com","location":"Chennai, India","jobType":"Full-time","workplaceType":"On-site","numberOfOpenings":5,"requiredSkills":["HTML","CSS","JavaScript"],"preferredSkills":["React","Angular","Vue"],"minExperience":0,"maxExperience":2,"educationLevel":"Bachelor's Degree","salaryMin":300000,"salaryMax":500000,"description":"Zoho is hiring Junior Frontend Developers for our Chennai office. This is an excellent opportunity for freshers and early-career developers to grow in a product company.\n\nResponsibilities:\n- Build user interfaces using HTML, CSS, and JavaScript\n- Convert design mockups to responsive web pages\n- Fix bugs and improve application performance\n- Learn and adopt new frontend technologies\n- Participate in daily standups and sprint planning\n\nRequired Skills:\n- HTML5 semantic markup\n- CSS3 including Flexbox and Grid\n- JavaScript fundamentals and DOM manipulation\n\nPreferred Skills:\n- Any modern framework: React, Angular, or Vue\n- Understanding of responsive design\n- Basic knowledge of version control\n\nEducation: Bachelor's degree in any field\nExperience: Freshers welcome, 0-2 years experience"},
    {"title":"Java Backend Developer","company":"Cognizant","recruiter_email":"recruiter2@test.com","location":"Pune, India","jobType":"Full-time","workplaceType":"On-site","numberOfOpenings":3,"requiredSkills":["Java","Spring Boot","MySQL","Microservices"],"preferredSkills":["Docker","AWS","Jenkins"],"minExperience":3,"maxExperience":6,"educationLevel":"Bachelor's Degree","salaryMin":800000,"salaryMax":1500000,"description":"Cognizant is seeking a Java Backend Developer for our Pune delivery center. You will build enterprise-grade Java applications using Spring Boot and microservices architecture.\n\nResponsibilities:\n- Develop Java backend services using Spring Boot\n- Design microservices with proper API contracts\n- Manage MySQL databases with JPA/Hibernate\n- Write unit tests with JUnit and Mockito\n- Participate in architecture and design reviews\n\nRequired Skills:\n- Core Java with strong OOP fundamentals\n- Spring Boot framework expertise\n- MySQL database development\n- Microservices architecture patterns\n\nPreferred Skills:\n- Docker containerization\n- AWS deployment experience\n- Jenkins CI/CD pipelines\n\nEducation: Bachelor's degree in Computer Science or related field\nExperience: Minimum 3 years of Java development"},
    {"title":"Cloud Architect","company":"Deloitte","recruiter_email":"recruiter3@test.com","location":"Bangalore, India","jobType":"Full-time","workplaceType":"Hybrid","numberOfOpenings":1,"requiredSkills":["AWS","Azure","Kubernetes","Terraform","Docker"],"preferredSkills":["Python","Jenkins","Ansible"],"minExperience":5,"maxExperience":10,"educationLevel":"Master's Degree","salaryMin":2500000,"salaryMax":4500000,"description":"Deloitte India is looking for an experienced Cloud Architect to lead cloud transformation initiatives for enterprise clients. This senior role requires deep expertise across multiple cloud platforms.\n\nResponsibilities:\n- Design multi-cloud architecture spanning AWS and Azure\n- Lead Kubernetes cluster design and management\n- Define infrastructure as code standards using Terraform\n- Architect disaster recovery and high availability solutions\n- Guide engineering teams on cloud best practices\n\nRequired Skills:\n- AWS services and architecture patterns\n- Azure services and architecture patterns\n- Kubernetes advanced concepts and administration\n- Terraform for multi-cloud IaC\n- Docker and container orchestration\n\nPreferred Skills:\n- Python scripting for automation\n- Jenkins pipeline architecture\n- Ansible for configuration management\n\nEducation: Master's degree preferred\nExperience: Minimum 5 years of cloud architecture experience"},
    {"title":"Data Scientist","company":"Flipkart","recruiter_email":"recruiter1@test.com","location":"Bangalore, India","jobType":"Full-time","workplaceType":"Hybrid","numberOfOpenings":2,"requiredSkills":["Python","Pandas","Scikit-learn","Machine Learning","SQL"],"preferredSkills":["NumPy","Deep Learning","TensorFlow"],"minExperience":2,"maxExperience":5,"educationLevel":"Master's Degree","salaryMin":1500000,"salaryMax":2500000,"description":"Flipkart is hiring a Data Scientist to join our recommendation and personalization team. You will build ML models that impact millions of users daily.\n\nResponsibilities:\n- Build and deploy machine learning models for product recommendations\n- Analyze user behavior data to derive actionable insights\n- Design feature engineering pipelines for model training\n- Conduct A/B tests to measure model impact\n- Collaborate with engineering teams for model deployment\n\nRequired Skills:\n- Python for data science and ML\n- Pandas for data manipulation\n- Scikit-learn for classical ML algorithms\n- Machine learning fundamentals and evaluation\n- SQL for data extraction and analysis\n\nPreferred Skills:\n- NumPy for numerical computing\n- Deep learning experience\n- TensorFlow or PyTorch\n\nEducation: Master's degree in CS, Statistics, or related field\nExperience: Minimum 2 years of data science experience"},
]

# Application mapping: each candidate -> [high_match_job, medium_match_job, low_match_job] (1-indexed job numbers)
APPLICATION_MAP = {
    "ananya.sharma@test.com": [1, 6, 5],     # React Frontend(H), Full Stack(M), DevOps(L)
    "ravi.teja@test.com": [1, 7, 4],          # React Frontend(H), Junior FE(M), ML Engineer(L)
    "divya.menon@test.com": [7, 1, 8],        # Junior FE(H), React FE(M), Java Backend(L)
    "karthik.raj@test.com": [1, 6, 10],       # React Frontend(H), Full Stack(M), Data Scientist(L)
    "pooja.gupta@test.com": [7, 1, 2],        # Junior FE(H), React FE(M), Sr Python(L)
    "arun.kumar@test.com": [2, 10, 1],        # Sr Python(H), Data Scientist(M), React FE(L)
    "meghana.rao@test.com": [8, 5, 3],        # Java Backend(H), DevOps(M), Data Analyst(L)
    "farhan.ahmed@test.com": [6, 2, 9],       # Full Stack(H), Sr Python(M), Cloud Architect(L)
    "sneha.iyer@test.com": [2, 5, 7],         # Sr Python(H), DevOps(M), Junior FE(L)
    "vikram.desai@test.com": [5, 9, 3],       # DevOps(H), Cloud Architect(M), Data Analyst(L)
    "priya.patel@test.com": [3, 10, 5],       # Data Analyst(H), Data Scientist(M), DevOps(L)
    "rohit.saxena@test.com": [4, 10, 1],      # ML Engineer(H), Data Scientist(M), React FE(L)
    "lakshmi.nair@test.com": [3, 10, 8],      # Data Analyst(H), Data Scientist(M), Java Backend(L)
    "siddharth.jain@test.com": [10, 4, 6],    # Data Scientist(H), ML Engineer(M), Full Stack(L)
    "tanvi.deshmukh@test.com": [3, 7, 9],     # Data Analyst(H), Junior FE(M), Cloud Architect(L)
    "ajay.mishra@test.com": [5, 9, 3],        # DevOps(H), Cloud Architect(M), Data Analyst(L)
    "neha.kapoor@test.com": [5, 9, 1],        # DevOps(H), Cloud Architect(M), React FE(L)
    "srinivas.rao@test.com": [5, 9, 8],       # DevOps(H), Cloud Architect(M), Java Backend(L)
    "deepak.thakur@test.com": [5, 9, 10],     # DevOps(H), Cloud Architect(M), Data Scientist(L)
    "amit.patil@test.com": [6, 1, 4],         # Full Stack(H), React FE(M), ML Engineer(L)
    "swati.kulkarni@test.com": [6, 2, 5],     # Full Stack(H), Sr Python(M), DevOps(L)
    "manish.pandey@test.com": [6, 8, 5],      # Full Stack(H), Java Backend(M-edge), DevOps(L)
    "sakshi.joshi@test.com": [7, 3, 9],       # Junior FE(H), Data Analyst(M), Cloud Architect(L)
    "nikhil.sharma@test.com": [7, 8, 4],      # Junior FE(H), Java Backend(M), ML Engineer(L)
    "ishita.agarwal@test.com": [7, 6, 2],     # Junior FE(H), Full Stack(M), Sr Python(L)
}
